name: Static analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis-eslint:
    name: ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*", "16.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: node_modules/.bin/eslint .
